[package]
name = "paper-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"
pollster = "0.3.0"
winit = { version = "0.29.3", features = ["rwh_05"] }
wgpu = "0.18.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
glam = "0.24.2"
rand = "0.8.5"